name: pos
description: Mobile POS
publish_to: 'none'
version: 1.0.6+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bluetooth_thermal_printer: ^0.0.6
  change_app_package_name: ^1.0.0
  cloud_firestore: ^1.0.7
  cupertino_icons: ^1.0.2
  dartz: ^0.9.2
  date_range_picker: ^1.0.7
  equatable: ^2.0.3
  esc_pos_utils: ^1.0.0
  excel: ^1.1.5
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  flutter_bloc: ^7.1.0
  flutter_masked_text: ^0.8.0
  flutter_slidable: ^0.5.7
  freezed_annotation: ^0.12.0
  get_it: ^4.0.4
  injectable: ^1.0.4
  intl: ^0.17.0
  open_file: ^3.2.1
  package_info: ^2.0.0
  path_provider: ^2.0.1
  syncfusion_flutter_charts: ^19.1.63-beta
  syncfusion_flutter_core: ^19.1.63-beta
  syncfusion_flutter_datagrid: ^19.1.63-beta
  syncfusion_flutter_pdf: ^19.1.63-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: null
  flutter_launcher_icons: "^0.8.1"
  flutter_launcher_name: "^0.0.1"
  flutter_native_splash: ^0.2.8
  freezed: ^0.12.7
  injectable_generator: ^1.0.4

flutter_launcher_name:
  name: "Mobile POS"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/launcher_icon.png"

flutter_native_splash:
  color: "#22343C"
  image: "assets/icon/launcher_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/launcher_icon.png
    - assets/icon/company_icon.png
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/font/DMSans-Regular.ttf
        - asset: assets/font/DMSans-Medium.ttf
          weight: 500
        - asset: assets/font/DMSans-Bold.ttf
          weight: 700
